#!/bin/bash
set -e

# This script initializes the PostgreSQL database for the ORM benchmark
# It runs automatically when the container starts for the first time

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- Create sample TPC-H tables for benchmarking
    
    CREATE TABLE IF NOT EXISTS lineitem (
        l_orderkey BIGINT,
        l_partkey BIGINT,
        l_suppkey BIGINT,
        l_linenumber INTEGER,
        l_quantity DECIMAL(15,2),
        l_extendedprice DECIMAL(15,2),
        l_discount DECIMAL(15,2),
        l_tax DECIMAL(15,2),
        l_returnflag CHAR(1),
        l_linestatus CHAR(1),
        l_shipdate DATE,
        l_commitdate DATE,
        l_receiptdate DATE,
        l_shipinstruct CHAR(25),
        l_shipmode CHAR(10),
        l_comment VARCHAR(44)
    );

    CREATE TABLE IF NOT EXISTS orders (
        o_orderkey BIGINT PRIMARY KEY,
        o_custkey BIGINT,
        o_orderstatus CHAR(1),
        o_totalprice DECIMAL(15,2),
        o_orderdate DATE,
        o_orderpriority CHAR(15),
        o_clerk CHAR(15),
        o_shippriority INTEGER,
        o_comment VARCHAR(79)
    );

    CREATE TABLE IF NOT EXISTS customer (
        c_custkey BIGINT PRIMARY KEY,
        c_name VARCHAR(25),
        c_address VARCHAR(40),
        c_nationkey BIGINT,
        c_phone CHAR(15),
        c_acctbal DECIMAL(15,2),
        c_mktsegment CHAR(10),
        c_comment VARCHAR(117)
    );

    CREATE TABLE IF NOT EXISTS part (
        p_partkey BIGINT PRIMARY KEY,
        p_name VARCHAR(55),
        p_mfgr CHAR(25),
        p_brand CHAR(10),
        p_type VARCHAR(25),
        p_size INTEGER,
        p_container CHAR(10),
        p_retailprice DECIMAL(15,2),
        p_comment VARCHAR(23)
    );

    CREATE TABLE IF NOT EXISTS supplier (
        s_suppkey BIGINT PRIMARY KEY,
        s_name CHAR(25),
        s_address VARCHAR(40),
        s_nationkey BIGINT,
        s_phone CHAR(15),
        s_acctbal DECIMAL(15,2),
        s_comment VARCHAR(101)
    );

    CREATE TABLE IF NOT EXISTS partsupp (
        ps_partkey BIGINT,
        ps_suppkey BIGINT,
        ps_availqty INTEGER,
        ps_supplycost DECIMAL(15,2),
        ps_comment VARCHAR(199),
        PRIMARY KEY (ps_partkey, ps_suppkey)
    );

    CREATE TABLE IF NOT EXISTS nation (
        n_nationkey BIGINT PRIMARY KEY,
        n_name CHAR(25),
        n_regionkey BIGINT,
        n_comment VARCHAR(152)
    );

    CREATE TABLE IF NOT EXISTS region (
        r_regionkey BIGINT PRIMARY KEY,
        r_name CHAR(25),
        r_comment VARCHAR(152)
    );

    -- No sample data. This script previously inserted 1,000 rows of random()
    -- data into LINEITEM on first container start. Anyone who brought the
    -- container up as documented and then loaded TPC-H got the benchmark
    -- dataset plus a thousand synthetic rows: 59,987,052 rows at SF10 rather
    -- than 59,986,052, with l_shipdate values relative to the day the container
    -- happened to start. Q1 and Q6 aggregate over exactly those columns, so the
    -- error was small enough to look like noise and large enough to be wrong.
    -- The dataset is generated by DuckDB and loaded by
    -- scripts/1-setup/load_pg.py; this file only creates the schema.

    -- Grant all privileges to benchmark user
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $POSTGRES_USER;

    -- No secondary indexes. This script previously ended with
    --
    --     CREATE INDEX IF NOT EXISTS idx_lineitem_shipdate ON lineitem(l_shipdate);
    --     CREATE INDEX IF NOT EXISTS idx_lineitem_orderkey ON lineitem(l_orderkey);
    --
    -- under the heading "create indexes for better performance". Those are two
    -- of the fifteen secondary indexes in data/indexes/postgres_indexes.sql that
    -- *define* the indexed configuration, and they are the two that matter most:
    -- l_shipdate is the filter in Q01, Q03, Q06, Q12, Q14 and Q19, and
    -- l_orderkey is the join column for every lineitem-orders join in the
    -- workload. A database built from this file therefore carried part of the
    -- indexed design under the non-indexed label, on the largest table.
    --
    -- The same defect was found and fixed in the MySQL schema; see the header of
    -- scripts/1-setup/schema_mysql.sql. It did not reach any published number
    -- here - the 88 non-indexed PostgreSQL plans in
    -- results/corrected/execution_plans.jsonl reference neither index, while the
    -- indexed plans reference them 16 and 15 times - so the campaign that
    -- produced the current rows was built some other way. It would have
    -- contaminated the next one, because a fresh container does run this script.
    --
    -- The indexed configuration is this schema plus postgres_indexes.sql, and
    -- nothing else.

    \echo 'Database initialization complete!'
EOSQL
