#!/usr/bin/env python3
"""Generate and load TPC-C, seeded, streaming, one vendor at a time.

    python3 load_tpcc.py --dbms postgresql
    python3 load_tpcc.py --dbms mysql --seed 42
    python3 load_tpcc.py --dbms sqlserver --schema-only

Replaces `generate_tpcc_data.py` plus the three `setup_tpcc_*.sh` scripts, for
three reasons.

*The generator was not reproducible.* It calls `random.randint` with no seed, so
every run produced a different database. TPC-H in this package is generated by
DuckDB from a fixed seed and is byte-identical on every machine; TPC-C was not,
which means a TPC-C measurement could not be repeated even in principle. The
seed here defaults to 42 and is recorded in the load log.

*The loaders did not work.* `setup_tpcc_postgres.sh` sources the schema from
`scripts/setup/`, a directory that does not exist - it is `scripts/1-setup/` -
and COPYs from `/tpcc-data/*.tbl.clean`, which is neither a path docker-compose
mounts nor a filename the generator writes (it writes `.tbl`, and nothing
produces the `.clean` variant). None of the three could have run.

*The intermediate files buy nothing.* The TPC-H pipeline moved to streaming for
the same reason: writing several million rows to disk to read them straight back
costs time and space and adds a format to get wrong.

Cardinalities come from `tpcc_config`, so the loaded database and the
transactions that measure it cannot disagree about how many warehouses exist -
a mismatch there makes most transactions fail on a missing row, and a harness
that counts a returned dict as success would report that as throughput.
"""

import argparse
import io
import os
import random
import string
import sys
import time
from datetime import datetime, timedelta
from decimal import Decimal

sys.path.insert(
    0,
    os.path.abspath(
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
    ),
)

import tpcc_config as cfg

ORDERS_PER_DISTRICT = int(os.environ.get("TPCC_ORDERS", "3000"))
HISTORY_PER_DISTRICT = int(os.environ.get("TPCC_HISTORY", "1000"))

# Load order respects the foreign keys in create_tpcc_schema_*.sql.
ORDER = [
    "warehouse",
    "item",
    "district",
    "customer",
    "stock",
    "order",
    "new_order",
    "order_line",
    "history",
]

NCOLS = {
    "warehouse": 9,
    "item": 5,
    "district": 11,
    "customer": 21,
    "stock": 17,
    "order": 8,
    "new_order": 3,
    "order_line": 10,
    "history": 8,
}


def _s(rng, n, prefix=""):
    return prefix + "".join(
        rng.choice(string.ascii_letters) for _ in range(max(0, n - len(prefix)))
    )


def _phone(rng):
    return "".join(rng.choice(string.digits) for _ in range(16))


def _zip(rng):
    return "".join(rng.choice(string.digits) for _ in range(4)) + "11111"


def rows(table, rng):
    """Yield tuples for `table`, in the column order the schema declares."""
    W, D = cfg.WAREHOUSES, cfg.DISTRICTS_PER_WAREHOUSE
    C, I = cfg.CUSTOMERS_PER_DISTRICT, cfg.ITEMS

    if table == "warehouse":
        for w in range(1, W + 1):
            yield (
                w,
                _s(rng, 10, "W"),
                _s(rng, 20),
                _s(rng, 20),
                _s(rng, 20),
                _s(rng, 2),
                _zip(rng),
                Decimal(rng.randrange(0, 2000)) / 10000,
                Decimal("300000.00"),
            )

    elif table == "item":
        for i in range(1, I + 1):
            yield (
                i,
                rng.randint(1, 10000),
                _s(rng, 24, "ITEM"),
                Decimal(rng.randrange(100, 10000)) / 100,
                _s(rng, 50),
            )

    elif table == "district":
        for w in range(1, W + 1):
            for d in range(1, D + 1):
                # d_next_o_id starts one past the pre-loaded orders, so a
                # New-Order transaction allocates an id that does not collide.
                yield (
                    d,
                    w,
                    _s(rng, 10, "D"),
                    _s(rng, 20),
                    _s(rng, 20),
                    _s(rng, 20),
                    _s(rng, 2),
                    _zip(rng),
                    Decimal(rng.randrange(0, 2000)) / 10000,
                    Decimal("30000.00"),
                    ORDERS_PER_DISTRICT + 1,
                )

    elif table == "customer":
        base = datetime(2025, 1, 1)
        for w in range(1, W + 1):
            for d in range(1, D + 1):
                for c in range(1, C + 1):
                    yield (
                        c,
                        d,
                        w,
                        _s(rng, 16, "F"),
                        "OE",
                        _s(rng, 16, "L"),
                        _s(rng, 20),
                        _s(rng, 20),
                        _s(rng, 20),
                        _s(rng, 2),
                        _zip(rng),
                        _phone(rng),
                        base,
                        "GC" if rng.random() > 0.1 else "BC",
                        Decimal("50000.00"),
                        Decimal(rng.randrange(0, 5000)) / 10000,
                        Decimal("-10.00"),
                        Decimal("10.00"),
                        1,
                        0,
                        _s(rng, 100),
                    )

    elif table == "stock":
        for w in range(1, W + 1):
            for i in range(1, I + 1):
                dists = [_s(rng, 24) for _ in range(10)]
                yield (i, w, rng.randint(10, 100), *dists, 0, 0, 0, _s(rng, 50))

    elif table == "order":
        base = datetime(2025, 1, 1)
        for w in range(1, W + 1):
            for d in range(1, D + 1):
                for o in range(1, ORDERS_PER_DISTRICT + 1):
                    yield (
                        o,
                        d,
                        w,
                        rng.randint(1, C),
                        base + timedelta(seconds=o),
                        rng.randint(1, 10) if o < ORDERS_PER_DISTRICT * 0.7 else None,
                        rng.randint(5, 15),
                        1,
                    )

    elif table == "new_order":
        # The newest ~30% of each district's orders are undelivered, which is
        # what Delivery consumes. Fixed rather than random so the count is known.
        start = int(ORDERS_PER_DISTRICT * 0.7) + 1
        for w in range(1, W + 1):
            for d in range(1, D + 1):
                for o in range(start, ORDERS_PER_DISTRICT + 1):
                    yield (o, d, w)

    elif table == "order_line":
        base = datetime(2025, 1, 1)
        for w in range(1, W + 1):
            for d in range(1, D + 1):
                for o in range(1, ORDERS_PER_DISTRICT + 1):
                    for n in range(1, rng.randint(5, 15) + 1):
                        yield (
                            o,
                            d,
                            w,
                            n,
                            rng.randint(1, I),
                            w,
                            base + timedelta(seconds=o),
                            5,
                            Decimal(rng.randrange(0, 999999)) / 100,
                            _s(rng, 24),
                        )

    elif table == "history":
        base = datetime(2025, 1, 1)
        for w in range(1, W + 1):
            for d in range(1, D + 1):
                for _ in range(HISTORY_PER_DISTRICT):
                    yield (
                        rng.randint(1, C),
                        d,
                        w,
                        d,
                        w,
                        base,
                        Decimal(rng.randrange(100, 500000)) / 100,
                        _s(rng, 24),
                    )


# ----------------------------------------------------------------- per vendor


def quoted(table, dbms):
    """ORDER is reserved in every one of these dialects."""
    if table != "order":
        return table
    return {
        "postgresql": '"order"',
        "mysql": "`order`",
        "sqlserver": "[order]",
        "oracle": '"ORDER"',
    }[dbms]


def load_postgresql(table, gen, batch=50_000):
    import psycopg2

    dsn = os.environ.get(
        "PG_DSN", "host=127.0.0.1 port=55432 dbname=tpcc user=benchmark password=bench"
    )
    cn = psycopg2.connect(dsn)
    n, t0 = 0, time.perf_counter()
    with cn.cursor() as cur:
        buf, k = io.StringIO(), 0
        for r in gen:
            buf.write("\t".join("\\N" if v is None else str(v) for v in r) + "\n")
            k += 1
            n += 1
            if k >= batch:
                buf.seek(0)
                cur.copy_expert(
                    "COPY %s FROM STDIN WITH (FORMAT text)"
                    % quoted(table, "postgresql"),
                    buf,
                )
                buf, k = io.StringIO(), 0
        if k:
            buf.seek(0)
            cur.copy_expert(
                "COPY %s FROM STDIN WITH (FORMAT text)" % quoted(table, "postgresql"),
                buf,
            )
    cn.commit()
    cn.close()
    return n, time.perf_counter() - t0


def load_dbapi(table, gen, dbms, batch=20_000):
    """MySQL, SQL Server and Oracle: batched executemany."""
    if dbms == "oracle":
        import oracledb

        cn = oracledb.connect(
            user=os.environ.get("ORA_TPCC_USER", "tpcc"),
            password=os.environ.get("ORA_TPCC_PASS", "bench"),
            dsn=os.environ.get("ORA_DSN", "127.0.0.1:41521/FREEPDB1"),
        )
        # Oracle binds by position with :1, :2, ...
        ph = ",".join(":%d" % i for i in range(1, NCOLS[table] + 1))
    elif dbms == "mysql":
        import MySQLdb  # mysqlclient, not PyMySQL (C31)

        # Read from the environment, like the PostgreSQL branch above. These
        # were fixed at port 33306 and root/bench, which are the container's
        # values and belong to no engine on a host where the servers are
        # installed natively: MySQL answers on 3306 as `benchmark`. A hardcoded
        # DSN in a loader does not fail quietly - it cannot connect at all - but
        # it does make the script unusable outside the setup it was written in,
        # and campaign-env.sh already publishes the right names.
        cn = MySQLdb.connect(
            host=os.environ.get("MYSQL_HOST", "127.0.0.1"),
            port=int(os.environ.get("MYSQL_PORT", "33306")),
            user=os.environ.get("MYSQL_USER", "root"),
            password=os.environ.get("MYSQL_PASSWORD", "bench"),
            database=os.environ.get("MYSQL_DB", "tpcc"),
            autocommit=False,
        )
        ph = ",".join(["%s"] * NCOLS[table])
    else:
        import pyodbc

        drv = max(
            (d for d in pyodbc.drivers() if "SQL Server" in d),
            key=lambda s: int("".join(c for c in s if c.isdigit()) or 0),
        )
        cn = pyodbc.connect(
            "DRIVER={%s};SERVER=%s,%s;DATABASE=%s;UID=%s;PWD=%s;"
            "TrustServerCertificate=yes"
            % (
                drv,
                os.environ.get("SQLSERVER_HOST", "127.0.0.1"),
                os.environ.get("SQLSERVER_PORT", "1433"),
                os.environ.get("SQLSERVER_DB", "tpcc"),
                os.environ.get("SQLSERVER_USER", "sa"),
                os.environ.get(
                    "SQLSERVER_SA_PASSWORD",
                    os.environ.get("SQLSERVER_PASSWORD", "YourStrong!Passw0rd"),
                ),
            ),
            autocommit=False,
        )
        ph = ",".join(["?"] * NCOLS[table])

    cur = cn.cursor()
    if dbms == "sqlserver":
        cur.fast_executemany = True
    stmt = "INSERT INTO %s VALUES (%s)" % (quoted(table, dbms), ph)
    n, t0, chunk = 0, time.perf_counter(), []
    for r in gen:
        chunk.append(list(r))
        if len(chunk) >= batch:
            cur.executemany(stmt, chunk)
            cn.commit()
            n += len(chunk)
            chunk = []
    if chunk:
        cur.executemany(stmt, chunk)
        cn.commit()
        n += len(chunk)
    cur.close()
    cn.close()
    return n, time.perf_counter() - t0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--dbms", required=True, choices=["postgresql", "mysql", "sqlserver", "oracle"]
    )
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--tables", default="")
    args = ap.parse_args()

    want = [t.strip() for t in args.tables.split(",")] if args.tables else ORDER
    print("TPC-C load: %s, seed %d" % (args.dbms, args.seed))
    print(cfg.summary())
    print()

    total = 0
    for t in ORDER:
        if t not in want:
            continue
        # A fresh RNG per table, seeded from the base seed and the table name,
        # so loading a subset reproduces exactly the rows a full load produced.
        rng = random.Random("%d:%s" % (args.seed, t))
        gen = rows(t, rng)
        if args.dbms == "postgresql":
            n, dt = load_postgresql(t, gen)
        else:
            n, dt = load_dbapi(t, gen, args.dbms)
        total += n
        print("  %-12s %10s rows in %5.0fs" % (t, format(n, ","), dt), flush=True)

    print("\n  %s rows total" % format(total, ","))
    return 0


if __name__ == "__main__":
    sys.exit(main())
