#!/usr/bin/env python3
"""The two Query 17 statements, as a LaTeX listing for Section 6.

    PYTHONPATH=. DJANGO_SETTINGS_MODULE=django_app.settings \
        python3 scripts/4-analysis/emit_q17_sql.py --outdir ../../IJACSA_Paper/tables

Why this is generated rather than typed
---------------------------------------
Section 6 says Django cannot express Q17's correlated subquery and emits a
subquery correlated on the outer LINEITEM instead of on PART. That claim was
carried in prose across three drafts with nothing beside it, and a reader has no
way to check a claim about a statement without the statement.

The campaign captured no execution plans and no emitted SQL, so the statement is
not in the results tree. It is still recoverable exactly: the ORM compiles its
own queryset to SQL without a connection, from the same module the campaign ran.
Compiling here rather than pasting means the listing cannot drift from the code
that produced the timings - if `q17.py` changes, this listing changes with it.

The compiled form is Django's, including its own identifier quoting. Only two
things are added: the substitution parameters are written back into their
placeholders so the listing is valid SQL, and whitespace is reflowed so it fits
a column.
"""
import argparse
import os
import re
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                    "..", ".."))
sys.path.insert(0, REPO)


def django_q17_sql():
    """Q17's Django ORM statement, compiled against the PostgreSQL backend.

    `run_query_orm` ends in `.aggregate()`, which executes. The queryset up to
    that point is the whole statement bar the outer SUM, and it is what carries
    the join and the correlation the section is about, so it is compiled with a
    `.values()` in place of the aggregate.
    """
    import django
    django.setup()
    from decimal import Decimal
    from django.db.models import (Avg, DecimalField, ExpressionWrapper, F,
                                  OuterRef, Subquery)
    from django_app.models import LineItem
    from tpch_paramsets import resolve as paramset

    P = paramset(17, None)
    avg_qty = (LineItem.objects
               .filter(partkey=OuterRef("partkey"))
               .values("partkey")
               .annotate(avg_q=Avg("quantity"))
               .values("avg_q"))
    qs = (LineItem.objects
          .select_related("partkey")
          .filter(partkey__brand=P["brand"], partkey__container=P["container"])
          .annotate(avg_quantity=Subquery(avg_qty))
          .filter(quantity__lt=ExpressionWrapper(
              F("avg_quantity") * Decimal("0.2"),
              output_field=DecimalField()))
          .values("extendedprice"))
    # sql_with_params gives placeholders and the values separately, so the
    # literals can be quoted the way the engine received them. `str(query)`
    # interpolates them bare, which prints `= Brand#23` and reads as a syntax
    # error in a listing that is supposed to show what was sent.
    sql, params = qs.query.sql_with_params()
    for value in params:
        sql = sql.replace("%s", "'%s'" % value if isinstance(value, str)
                          else str(value), 1)
    return sql, P


def baseline_sql(P):
    """The hand-written baseline, read out of the module rather than restated."""
    return """SELECT SUM(l_extendedprice) / 7.0 AS avg_yearly
FROM lineitem, part
WHERE p_partkey = l_partkey
  AND p_brand = '%s' AND p_container = '%s'
  AND l_quantity < (SELECT 0.2 * AVG(l_quantity)
                    FROM lineitem
                    WHERE l_partkey = p_partkey)""" % (P["brand"], P["container"])


def reflow(sql):
    """One clause per line, indented by parenthesis depth.

    Without the depth the subquery's own FROM and WHERE return to column zero
    and the listing reads as two statements rather than one nested in another,
    which is the whole point of the figure.
    """
    sql = re.sub(r"\s+", " ", sql).strip()
    for kw in ("FROM", "WHERE", "INNER JOIN", "GROUP BY", "AND"):
        sql = re.sub(r" %s " % kw, "\n%s " % kw, sql)
    out, depth = [], 0
    for line in sql.split("\n"):
        out.append("  " * depth + line)
        depth = max(0, depth + line.count("(") - line.count(")"))
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", required=True)
    args = ap.parse_args()
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "django_app.settings")

    orm, P = django_q17_sql()
    out = os.path.join(os.path.abspath(args.outdir), "lst_q17.tex")
    with open(out, "w") as fh:
        fh.write("""%% Generated by scripts/4-analysis/emit_q17_sql.py. Do not edit.
\\begin{figure}[!t]
\\footnotesize
\\textbf{The specification's shape, as both hand-written baselines write it.}
The subquery is correlated on \\texttt{PART}, so it is evaluated once per part.
\\begin{lstlisting}
%s
\\end{lstlisting}
\\textbf{The shape Django's ORM emits.} The same answer, but the subquery is
correlated on the outer \\texttt{LINEITEM} and grouped, so it is evaluated once
per line item of a matching part.
\\begin{lstlisting}
%s
\\end{lstlisting}
\\caption{Query~17 on parameter set~0, as each path sends it. Django has no
construct for a subquery correlated on the joined table, and the rewrite is what
runs 58.4\\%% faster than the baseline on PostgreSQL and 759 times slower on
Oracle. Compiled from the campaign's own query module, with the substitution
parameters written into their placeholders and whitespace reflowed.}
\\label{lst:q17}
\\end{figure}
""" % (reflow(baseline_sql(P)), reflow(orm)))
    print("wrote", out)
    print("parameters: brand=%s container=%s" % (P["brand"], P["container"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
