-- MySQL initialization script for ORM benchmark
-- This script runs automatically when the container starts for the first time

USE tpch;

-- Create sample TPC-H tables for benchmarking

CREATE TABLE IF NOT EXISTS lineitem (
    l_orderkey BIGINT,
    l_partkey BIGINT,
    l_suppkey BIGINT,
    l_linenumber INT,
    l_quantity DECIMAL(15,2),
    l_extendedprice DECIMAL(15,2),
    l_discount DECIMAL(15,2),
    l_tax DECIMAL(15,2),
    l_returnflag CHAR(1),
    l_linestatus CHAR(1),
    l_shipdate DATE,
    l_commitdate DATE,
    l_receiptdate DATE,
    l_shipinstruct CHAR(25),
    l_shipmode CHAR(10),
    l_comment VARCHAR(44)
    -- No secondary indexes here, deliberately. This table previously declared
    -- INDEX idx_lineitem_shipdate and INDEX idx_lineitem_orderkey inline, which
    -- are two of the fifteen indexes that define the *indexed* configuration.
    -- A database built from this file therefore carried part of the indexed
    -- physical design while being measured as "non-indexed", and
    -- data/indexes/mysql_indexes.sql then failed on the duplicate index names
    -- when the indexed configuration was built on top of it.
    -- Non-indexed means primary keys only, matching docker/postgresql/init-db.sh.
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS orders (
    o_orderkey BIGINT PRIMARY KEY,
    o_custkey BIGINT,
    o_orderstatus CHAR(1),
    o_totalprice DECIMAL(15,2),
    o_orderdate DATE,
    o_orderpriority CHAR(15),
    o_clerk CHAR(15),
    o_shippriority INT,
    o_comment VARCHAR(79)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS customer (
    c_custkey BIGINT PRIMARY KEY,
    c_name VARCHAR(25),
    c_address VARCHAR(40),
    c_nationkey BIGINT,
    c_phone CHAR(15),
    c_acctbal DECIMAL(15,2),
    c_mktsegment CHAR(10),
    c_comment VARCHAR(117)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS part (
    p_partkey BIGINT PRIMARY KEY,
    p_name VARCHAR(55),
    p_mfgr CHAR(25),
    p_brand CHAR(10),
    p_type VARCHAR(25),
    p_size INT,
    p_container CHAR(10),
    p_retailprice DECIMAL(15,2),
    p_comment VARCHAR(23)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS supplier (
    s_suppkey BIGINT PRIMARY KEY,
    s_name CHAR(25),
    s_address VARCHAR(40),
    s_nationkey BIGINT,
    s_phone CHAR(15),
    s_acctbal DECIMAL(15,2),
    s_comment VARCHAR(101)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS partsupp (
    ps_partkey BIGINT,
    ps_suppkey BIGINT,
    ps_availqty INT,
    ps_supplycost DECIMAL(15,2),
    ps_comment VARCHAR(199),
    PRIMARY KEY (ps_partkey, ps_suppkey)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS nation (
    n_nationkey BIGINT PRIMARY KEY,
    n_name CHAR(25),
    n_regionkey BIGINT,
    n_comment VARCHAR(152)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS region (
    r_regionkey BIGINT PRIMARY KEY,
    r_name CHAR(25),
    r_comment VARCHAR(152)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- No sample data. This file previously ended with a populate_lineitem()
-- procedure that inserted 1,000 rows of RAND() data into LINEITEM on first
-- container start. Anyone who brought the container up as the README describes
-- and then loaded TPC-H got the benchmark dataset plus a thousand synthetic
-- rows, so LINEITEM held 59,987,052 rows at SF10 rather than 59,986,052, and
-- every aggregate over it was wrong by an amount too small to notice and too
-- large to ignore. The dataset is generated by DuckDB and loaded by
-- scripts/1-setup/load_mysql.py; there is no reason for this file to invent any.

-- Grant all privileges to benchmark user
GRANT ALL PRIVILEGES ON tpch.* TO 'benchmark'@'%';
FLUSH PRIVILEGES;

SELECT 'Database initialization complete!' AS Status;

